apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    type: backend
  template:
    metadata:
      name: backend-server
      labels:
        type: backend
    spec:
      containers:
        - name: backend-container
          image: golang-backend:1.0.1
