apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    type: backend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008

---
# The port which is specified here is the port of the service, the targetPort is the port on the service and nodePort is the port on the node where we can access the backend service
