apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgres-service
spec:
  type: ClusterIp
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: postgres-pod
    app: postgres-db
