apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      name: backend-server
      labels:
        type: backend
    spec:
      containers:
        - name: backend-container
          image: golang-backend:1.0.1
